version: "3.8"

networks:
  default:
    external:
      name: n8n-postgres-node-network

services:
  nodeapp:
    build: .
    ports:
      - "4000:4000"
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
